import { IOwner } from '../../../core/domain/owner.model';

export function getProductsData() {
  return [
    {
      id: '1000',
      code: 'f230fh0g3',
      name: 'Bamboo Watch',
      description: 'Product Description',
      image: 'bamboo-watch.jpg',
      price: 65,
      category: 'Accessories',
      quantity: 24,
      inventoryStatus: 'INSTOCK',
      rating: 5,
    },
    {
      id: '1001',
      code: 'nvklal433',
      name: 'Black Watch',
      description: 'Product Description',
      image: 'black-watch.jpg',
      price: 72,
      category: 'Accessories',
      quantity: 61,
      inventoryStatus: 'OUTOFSTOCK',
      rating: 4,
    },
    {
      id: '1002',
      code: 'zz21cz3c1',
      name: 'Blue Band',
      description: 'Product Description',
      image: 'blue-band.jpg',
      price: 79,
      category: 'Fitness',
      quantity: 2,
      inventoryStatus: 'LOWSTOCK',
      rating: 3,
    },
    {
      id: '1003',
      code: '244wgerg2',
      name: 'Blue T-Shirt',
      description: 'Product Description',
      image: 'blue-t-shirt.jpg',
      price: 29,
      category: 'Clothing',
      quantity: 25,
      inventoryStatus: 'INSTOCK',
      rating: 5,
    },
    {
      id: '1004',
      code: 'h456wer53',
      name: 'Bracelet',
      description: 'Product Description',
      image: 'bracelet.jpg',
      price: 15,
      category: 'Accessories',
      quantity: 73,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1005',
      code: 'av2231fwg',
      name: 'Brown Purse',
      description: 'Product Description',
      image: 'brown-purse.jpg',
      price: 120,
      category: 'Accessories',
      quantity: 0,
      inventoryStatus: 'OUTOFSTOCK',
      rating: 4,
    },
    {
      id: '1006',
      code: 'bib36pfvm',
      name: 'Chakra Bracelet',
      description: 'Product Description',
      image: 'chakra-bracelet.jpg',
      price: 32,
      category: 'Accessories',
      quantity: 5,
      inventoryStatus: 'LOWSTOCK',
      rating: 3,
    },
    {
      id: '1007',
      code: 'mbvjkgip5',
      name: 'Galaxy Earrings',
      description: 'Product Description',
      image: 'galaxy-earrings.jpg',
      price: 34,
      category: 'Accessories',
      quantity: 23,
      inventoryStatus: 'INSTOCK',
      rating: 5,
    },
    {
      id: '1008',
      code: 'vbb124btr',
      name: 'Game Controller',
      description: 'Product Description',
      image: 'game-controller.jpg',
      price: 99,
      category: 'Electronics',
      quantity: 2,
      inventoryStatus: 'LOWSTOCK',
      rating: 4,
    },
    {
      id: '1009',
      code: 'cm230f032',
      name: 'Gaming Set',
      description: 'Product Description',
      image: 'gaming-set.jpg',
      price: 299,
      category: 'Electronics',
      quantity: 63,
      inventoryStatus: 'INSTOCK',
      rating: 3,
    },
    {
      id: '1010',
      code: 'plb34234v',
      name: 'Gold Phone Case',
      description: 'Product Description',
      image: 'gold-phone-case.jpg',
      price: 24,
      category: 'Accessories',
      quantity: 0,
      inventoryStatus: 'OUTOFSTOCK',
      rating: 4,
    },
    {
      id: '1011',
      code: '4920nnc2d',
      name: 'Green Earbuds',
      description: 'Product Description',
      image: 'green-earbuds.jpg',
      price: 89,
      category: 'Electronics',
      quantity: 23,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1012',
      code: '250vm23cc',
      name: 'Green T-Shirt',
      description: 'Product Description',
      image: 'green-t-shirt.jpg',
      price: 49,
      category: 'Clothing',
      quantity: 74,
      inventoryStatus: 'INSTOCK',
      rating: 5,
    },
    {
      id: '1013',
      code: 'fldsmn31b',
      name: 'Grey T-Shirt',
      description: 'Product Description',
      image: 'grey-t-shirt.jpg',
      price: 48,
      category: 'Clothing',
      quantity: 0,
      inventoryStatus: 'OUTOFSTOCK',
      rating: 3,
    },
    {
      id: '1014',
      code: 'waas1x2as',
      name: 'Headphones',
      description: 'Product Description',
      image: 'headphones.jpg',
      price: 175,
      category: 'Electronics',
      quantity: 8,
      inventoryStatus: 'LOWSTOCK',
      rating: 5,
    },
    {
      id: '1015',
      code: 'vb34btbg5',
      name: 'Light Green T-Shirt',
      description: 'Product Description',
      image: 'light-green-t-shirt.jpg',
      price: 49,
      category: 'Clothing',
      quantity: 34,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1016',
      code: 'k8l6j58jl',
      name: 'Lime Band',
      description: 'Product Description',
      image: 'lime-band.jpg',
      price: 79,
      category: 'Fitness',
      quantity: 12,
      inventoryStatus: 'INSTOCK',
      rating: 3,
    },
    {
      id: '1017',
      code: 'v435nn85n',
      name: 'Mini Speakers',
      description: 'Product Description',
      image: 'mini-speakers.jpg',
      price: 85,
      category: 'Clothing',
      quantity: 42,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1018',
      code: '09zx9c0zc',
      name: 'Painted Phone Case',
      description: 'Product Description',
      image: 'painted-phone-case.jpg',
      price: 56,
      category: 'Accessories',
      quantity: 41,
      inventoryStatus: 'INSTOCK',
      rating: 5,
    },
    {
      id: '1019',
      code: 'mnb5mb2m5',
      name: 'Pink Band',
      description: 'Product Description',
      image: 'pink-band.jpg',
      price: 79,
      category: 'Fitness',
      quantity: 63,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1020',
      code: 'r23fwf2w3',
      name: 'Pink Purse',
      description: 'Product Description',
      image: 'pink-purse.jpg',
      price: 110,
      category: 'Accessories',
      quantity: 0,
      inventoryStatus: 'OUTOFSTOCK',
      rating: 4,
    },
    {
      id: '1021',
      code: 'pxpzczo23',
      name: 'Purple Band',
      description: 'Product Description',
      image: 'purple-band.jpg',
      price: 79,
      category: 'Fitness',
      quantity: 6,
      inventoryStatus: 'LOWSTOCK',
      rating: 3,
    },
    {
      id: '1022',
      code: '2c42cb5cb',
      name: 'Purple Gemstone Necklace',
      description: 'Product Description',
      image: 'purple-gemstone-necklace.jpg',
      price: 45,
      category: 'Accessories',
      quantity: 62,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1023',
      code: '5k43kkk23',
      name: 'Purple T-Shirt',
      description: 'Product Description',
      image: 'purple-t-shirt.jpg',
      price: 49,
      category: 'Clothing',
      quantity: 2,
      inventoryStatus: 'LOWSTOCK',
      rating: 5,
    },
    {
      id: '1024',
      code: 'lm2tny2k4',
      name: 'Shoes',
      description: 'Product Description',
      image: 'shoes.jpg',
      price: 64,
      category: 'Clothing',
      quantity: 0,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1025',
      code: 'nbm5mv45n',
      name: 'Sneakers',
      description: 'Product Description',
      image: 'sneakers.jpg',
      price: 78,
      category: 'Clothing',
      quantity: 52,
      inventoryStatus: 'INSTOCK',
      rating: 4,
    },
    {
      id: '1026',
      code: 'zx23zc42c',
      name: 'Teal T-Shirt',
      description: 'Product Description',
      image: 'teal-t-shirt.jpg',
      price: 49,
      category: 'Clothing',
      quantity: 3,
      inventoryStatus: 'LOWSTOCK',
      rating: 3,
    },
    {
      id: '1027',
      code: 'acvx872gc',
      name: 'Yellow Earbuds',
      description: 'Product Description',
      image: 'yellow-earbuds.jpg',
      price: 89,
      category: 'Electronics',
      quantity: 35,
      inventoryStatus: 'INSTOCK',
      rating: 3,
    },
    {
      id: '1028',
      code: 'tx125ck42',
      name: 'Yoga Mat',
      description: 'Product Description',
      image: 'yoga-mat.jpg',
      price: 20,
      category: 'Fitness',
      quantity: 15,
      inventoryStatus: 'INSTOCK',
      rating: 5,
    },
    {
      id: '1029',
      code: 'gwuby345v',
      name: 'Yoga Set',
      description: 'Product Description',
      image: 'yoga-set.jpg',
      price: 20,
      category: 'Fitness',
      quantity: 25,
      inventoryStatus: 'INSTOCK',
      rating: 8,
    },
  ];
}

export function getOwners(): IOwner[] {
  return [
    {
      id: '85105e7b-d8e4-40f9-899c-ad0e4561d1f5',
      imageUrl: 'http://placehold.it/64x64',
      name: 'Clarice Hutchinson',
      email: 'claricehutchinson@comcur.com',
      phone: '+1 (921) 422-2182',
      bio: 'Commodo et reprehenderit do id ut esse est nulla commodo quis. Id exercitation non aliquip nisi ea pariatur sunt velit ex ipsum sunt ipsum dolore. Sunt nulla elit occaecat minim elit ex et in labore tempor enim irure incididunt deserunt. Nisi et mollit deserunt sint cillum aute esse voluptate aliqua tempor. Consectetur duis enim ullamco minim sit incididunt duis.\r\n',
    },
    {
      id: 'dc95b1ce-52e7-45d5-8c9c-b93358a266c6',
      imageUrl: 'http://placehold.it/64x64',
      name: 'Catalina Raymond',
      email: 'catalinaraymond@comcur.com',
      phone: '+1 (849) 511-2644',
      bio: 'Dolore amet proident incididunt officia magna enim quis voluptate ad ex velit. Sit ea laborum reprehenderit aute tempor Lorem irure sint dolore. Est ullamco commodo deserunt aliqua irure proident eiusmod aliqua duis nostrud exercitation occaecat. Id nostrud elit proident aliqua non. Non ex deserunt dolor cillum consequat adipisicing id. Culpa esse occaecat veniam et velit sit dolor ea.\r\n',
    },
    {
      id: '790e9fa7-0b3a-4c19-b810-13ae59f8ed60',
      imageUrl: 'http://placehold.it/64x64',
      name: 'Henry Pugh',
      email: 'henrypugh@comcur.com',
      phone: '+1 (994) 470-2729',
      bio: 'Quis exercitation aliquip est Lorem est aliqua tempor aute labore. Dolore id ipsum laborum irure irure aliqua culpa pariatur veniam. Nisi qui et laboris in ipsum ea mollit incididunt sint do. Enim dolor culpa officia mollit aliqua duis minim excepteur duis tempor fugiat non consequat veniam.\r\n',
    },
    {
      id: 'cf709273-899a-4360-a294-06bfedd7f572',
      imageUrl: 'http://placehold.it/64x64',
      name: 'Pollard Carter',
      email: 'pollardcarter@comcur.com',
      phone: '+1 (866) 508-2856',
      bio: 'Id incididunt dolore reprehenderit deserunt aute culpa incididunt mollit pariatur et. Dolor ipsum id occaecat aute sint excepteur cillum enim. In duis eu anim nostrud eiusmod non anim id do reprehenderit eiusmod pariatur ea.\r\n',
    },
    {
      id: '11fb7529-5345-48f2-9284-0471a141e507',
      imageUrl: 'http://placehold.it/64x64',
      name: 'Elvia Sanders',
      email: 'elviasanders@comcur.com',
      phone: '+1 (992) 492-3012',
      bio: 'Anim labore incididunt labore irure aliquip et magna fugiat adipisicing do ea sint enim Lorem. Pariatur aute commodo laborum dolor laboris. Velit consequat voluptate et laborum commodo minim reprehenderit elit nisi ea aliquip qui amet id. Magna non ex cillum mollit. Consequat magna aute consectetur et. Consequat minim in cupidatat quis officia sit laborum aliqua voluptate esse laboris enim.\r\n',
    },
  ];
}
